# Generated by Django 4.2.3 on 2023-07-30 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Namayesh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='products', to='Namayesh.category'),
        ),
    ]
